announce = false

description = 'crc core'
website = 'https://github.com/altv-crc'
gamemode = 'Freeroam'

language = 'en'
modules = [ 'js-module' ]
name = 'TestServer'
players = 1024
port = 7788
tags = [ 'customTag1', 'customTag2', 'customTag3', 'customTag4' ]

resources = [
    "crc-instructional-buttons",
    "crc-native-menu",
    "crc-db",
    "crc-ban-handler",
    "crc-discord-login",
    "crc-preview-character",
    "crc-select-character",
    "crc-spawn",
    "crc-appearance",
    "crc-create-character",
    "watch-resources"
]

# Turn this off in production mode
debug = true

# Leave host as 0.0.0.0, don't change it.
host = '0.0.0.0'

[js-module]
global-webcrypto = true
global-fetch = true

[voice]
bitrate = 64000
